/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAsideRight: typeof import('./src/components/app/AppAsideRight.vue')['default']
    AppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AsideSetting: typeof import('./src/components/app/appAside/components/AsideSetting.vue')['default']
    AutoForm: typeof import('./src/components/autoForm/autoForm.vue')['default']
    BaseMenu: typeof import('./src/components/app/appAside/components/baseMenu/BaseMenu.vue')['default']
    BuffExplanation: typeof import('./src/components/BuffExplanation.vue')['default']
    CodeCanvas: typeof import('./src/components/codeCanvas/CodeCanvas.vue')['default']
    CommonDialog: typeof import('./src/components/CommonDialog.vue')['default']
    CommonFormDialog: typeof import('./src/components/CommonFormDialog.vue')['default']
    CommonFromDialog: typeof import('./src/components/CommonFromDialog.vue')['default']
    copy: typeof import('./src/components/autoForm/autoForm copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Extend: typeof import('./src/components/Extend.vue')['default']
    FormIcon: typeof import('./src/components/autoForm/components/FormIcon.vue')['default']
    FormTranslator: typeof import('./src/components/autoForm/components/FormTranslator.vue')['default']
    GlobalDialog: typeof import('./src/components/dialog/GlobalDialog.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconBlock: typeof import('./src/components/IconBlock.vue')['default']
    IconListItem: typeof import('./src/components/tabs/IconListItem.vue')['default']
    InlineMustache: typeof import('./src/components/inlineMustache/InlineMustache.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    KeyEvent: typeof import('./src/components/KeyEvent.vue')['default']
    KeyEventButton: typeof import('./src/components/KeyEventButton.vue')['default']
    KeyValueCard: typeof import('./src/components/KeyValueCard.vue')['default']
    NumberMark: typeof import('./src/components/NumberMark.vue')['default']
    Operator: typeof import('./src/components/codeCanvas/components/Operator.vue')['default']
    RouterHistory: typeof import('./src/components/routerHistory/RouterHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SpecialInlineBlock: typeof import('./src/components/inlineMustache/SpecialInlineBlock.vue')['default']
    Step: typeof import('./src/components/Step.vue')['default']
    SubButton: typeof import('./src/components/SubButton.vue')['default']
    TabsListItem: typeof import('./src/components/tabs/TabsListItem.vue')['default']
    TitleCardCore: typeof import('./src/components/titleCard/components/TitleCardCore.vue')['default']
    TitleCardDraggable: typeof import('./src/components/titleCard/TitleCardDraggable.vue')['default']
    TitleCardList: typeof import('./src/components/titleCardList/TitleCardList.vue')['default']
    TitleCardListItem: typeof import('./src/components/titleCardList/TitleCardListItem.vue')['default']
    TypeButton: typeof import('./src/components/typeButton/TypeButton.vue')['default']
    Workshop: typeof import('./src/components/app/appAside/components/workshop/Workshop.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
