/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideSetting: typeof import('./src/components/appAside/components/AsideSetting.vue')['default']
    AutoForm: typeof import('./src/components/autoForm/autoForm.vue')['default']
    BaseMenu: typeof import('./src/components/appAside/components/baseMenu/BaseMenu.vue')['default']
    CodeCanvas: typeof import('./src/components/codeCanvas/CodeCanvas.vue')['default']
    CommonDialog: typeof import('./src/components/CommonDialog.vue')['default']
    CommonFormDialog: typeof import('./src/components/CommonFormDialog.vue')['default']
    CommonFromDialog: typeof import('./src/components/CommonFromDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Extend: typeof import('./src/components/Extend.vue')['default']
    FormTranslator: typeof import('./src/components/autoForm/components/FormTranslator.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconBlock: typeof import('./src/components/IconBlock.vue')['default']
    IconListItem: typeof import('./src/components/tabs/IconListItem.vue')['default']
    Operator: typeof import('./src/components/codeCanvas/components/Operator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsListItem: typeof import('./src/components/tabs/TabsListItem.vue')['default']
    TypeButton: typeof import('./src/components/typeButton/TypeButton.vue')['default']
    Workshop: typeof import('./src/components/appAside/components/workshop/Workshop.vue')['default']
  }
}
