/** SCRIPT | generated by #/scripts */
[["Farmer", "PlainSettler"], ["Farmer", "ForestNative"], ["Farmer", "Tree"], ["Farmer", "Fish"], ["Rainmaker", "ForestNative", "Female"], ["Rainmaker", "PlainSettler", "Female"], ["Rainmaker", "Tree"], ["Archer", "PlainSettler"], ["Archer", "ForestNative"], ["Archer", "Tree"], ["Archer", "Fish"]];
