/** SCRIPT | generated by #/scripts */
export enum HumanLineage {
  PlainSettler = "o4VvHZRebQHV", ForestNative = "eovp79ed7hjd"
}

export enum YokaiLineage {
  Fish = "qm8v6qy0866p"
}

export enum ElvesLineage {
  Tree = "nn99qxmf8ki6"
}
