import { spawn } from "node:child_process";
import { readdir, unlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import { isArray } from "lodash";
import { mkPathDir } from "./path";

export async function clearFolder(folderPath: string): Promise<void> {
  const directory = await readdir(folderPath, { withFileTypes: true });

  await Promise.all(
    directory.map(async (file) => {
      const filePath = resolve(folderPath, file.name);
      if (file.isFile())
        await unlink(filePath);
    })
  );
}

export function writeFileToProject(path: string) {
  return (file: string | string[]) => {
    if (!existsSync(path)) mkPathDir(path);

    const injectString = `/** SCRIPT | generated by #/scripts */
    ${isArray(file) ? file.join("\n") : file}`;

    writeFile(path, injectString, (err) => {
      if (err) throw err;
    });
    spawn(process.platform.startsWith("win") ? "eslint.cmd" : "eslint", [path, "--fix"]).on("error", (err) => {
      throw err;
    });
    console.log("finished");
  };
}
