/** SCRIPT | generated by #/scripts */
export const professionFrom = [["Farmer", "PlainSettler"], ["Farmer", "ForestNative"], ["Farmer", "Tree"], ["Farmer", "Fish"], ["Rainmaker", "ForestNative", "Female"], ["Rainmaker", "PlainSettler", "Female"], ["Rainmaker", "Tree"], ["Hunter", "PlainSettler"], ["Hunter", "ForestNative"], ["Hunter", "Tree"], ["Hunter", "Fish"]];
